### ISSUE TITLE
RPI Flying Club

### ISSUE THREAD

**Issue by chadas5** [Alfriadox/rpi-servers#4]
##Server name:
> The name of the server or the club it is associated with.

RPI Flying Club

##Server link:
> Link to the server. Feel free to also include links to an associated website and
> social media accounts.

https://discord.gg/bjMzfjZ

## Tags:
> These are the tags that appear at the bottom of the server listing. These are not
> linked to anything but are useful for users trying to find a server using `Control-F`.

Club, Flying, Aviation, Aerospace, Hobby, Enthusiast

## Server description
> The description of the server or the associated club. 

The RPI Flying Club is a group of aviation enthusiasts who host a variety of events on and off campus! We do flying trips, attend air shows, host social and academic events, and host an annual ground school & flying lesson. No flying experience is required - all are welcome.

**Comment by chadas5** [comment]
![flying_club_logo](https://user-images.githubusercontent.com/65193141/100698423-63dc6100-3366-11eb-920d-0e491b75bff0.jpg)
 
^ club logo

**Comment by vcfxb** [comment]
Added!
