### ISSUE TITLE
RPI Design-Build-Fly

### ISSUE THREAD

**Issue by chadas5** [Alfriadox/rpi-servers#5]
##Server name:
> The name of the server or the club it is associated with.

RPI Design Build Fly (DBF)

##Server link:
> Link to the server. Feel free to also include links to an associated website and
> social media accounts.

https://discord.gg/VrPK5Pa3Mq

## Tags:
> These are the tags that appear at the bottom of the server listing. These are not
> linked to anything but are useful for users trying to find a server using `Control-F`.

Club, Design, Build, Fly, Engineering, Team, Aerospace, Airplane, Aviation

## Server description
> The description of the server or the associated club. 

RPI Design-Build-Fly (DBF) is a project-based team that builds an RC airplane annually for the AIAA DBF competition. We accept (and encourage) members from ALL majors and no prior RC airplane experience is required.

**Comment by chadas5** [comment]
![dbf_logo](https://user-images.githubusercontent.com/65193141/100698442-73f44080-3366-11eb-8cb2-7f16e7a146bd.png)

^ club logo

**Comment by vcfxb** [comment]
Added!
